#analisando textos
nome = str(input('Digite seu nome completo: ')).strip()
print('Analisando seu nome...')
print('Seu nome em maiúsculo é {}'.format(nome.upper()))
print('Seu nome em minúsculo é {}'.format(nome.lower()))
print('Seu nome tem {} letras'.format(len(nome) - nome.count (' ')))
print('Seu primeiro nome tem {} letras.'.format(nome.find(' ')))
lista = nome.split()
print(lista)
print('Seu primeiro nome é {}.'.format(lista[0]))
print('Seu sobrenome é {}.'.format(lista[1:]))